#!/bin/sh

BLANK='#000000'   # Black background
CLEAR='#e5e5e522' # Semi-transparent white (for the background effect)
DEFAULT='#0000eeE6'  # Blue (for default state - xterm blue)
TEXT='#e5e5e5'    # White text (to stand out on the dark background)
WRONG='#cd0000bb' # Red (for wrong input)
VERIFYING='#00cd00E6' # Cyan (for verifying state)


i3lock \
--insidever-color=$BLANK     \
--ringver-color=$VERIFYING   \
\
--insidewrong-color=$CLEAR   \
--ringwrong-color=$WRONG     \
\
--inside-color=$BLANK        \
--ring-color=$DEFAULT        \
--line-color=$BLANK          \
--separator-color=$DEFAULT   \
\
--verif-color=$TEXT          \
--wrong-color=$TEXT          \
--time-color=$TEXT           \
--date-color=$TEXT           \
--layout-color=$TEXT         \
--keyhl-color=$WRONG         \
--bshl-color=$WRONG          \
\
--screen 1                   \
--blur 9                     \
--clock                      \
--indicator                  \
--time-str="%H:%M:%S"        \
--date-str="%A, %Y-%m-%d"       \
--keylayout 1                \
