client.focused            = #1b1b1b #ffffff #cd0000 #ffff00 #ffffff
client.unfocused          = #2e2e2e #e5e5e5 #5c5cff #a9a9a9 #000000
client.focused_inactive   = #333333 #ffffff #cdcd00 #ffff00 #ffffff
client.urgent             = #5c0000 #ffffff #ff0000 #ff00ff #ffffff
